### ISSUE TITLE
Unable to join to TTN V3

### ISSUE THREAD

**Issue by BNNorman** [computenodes/dragino#15]
I know this code works well on V2 and you said it was tested on V3 but I created a V3 app and added a new test device but have been unable to join TTN.

Occasionally I can see, in the V3 console the message 'Accept join-request' but I don't receive the JOIN_ACCEPT. I'm wondering if the JOIN_ACCEPT is, for some odd reason, on a different frequency - that's something I haven't been able to explore as I haven't seen 'Accept join-request' messages for some time (hours) now and , I didn't keep the meta data to see if there was any more info.

As I said, your code works fine on V2 I get uplinks and can send downlinks with no bother. 

I've tried a few ttn-lw-cli commands - specifically --mac-settings.resets-f-fcnt, which seemed to work earlier but now does not so I may be on the wrong track with that one.

The dragino.ini shows fcount=1 and none for the session keys. I'm just using the simple test.py to establish a join.

So, I was wondering what you did to verify the code works on V3?

Thanks for any help.

**Comment by BNNorman** [comment]
It seems there are partial outages of V3 today - but that doesn't explain why I couldn't join yesterday (assuming it was 100% fit yesterday)

**Comment by pjb304** [comment]
I'm not sure what's going on there.  I have a node on my desk which I used to develop the code on and was (and have just tested it again) able to join and send messages.  I also have a sensor node on V3 that's sent over 5000 messages over the course of several weeks.

I've not used the cli to configure the devices - rather the web interface, I've attached a screenshot of the network settings that I'm using, in case there are any clues there.
![image](https://user-images.githubusercontent.com/1146400/124256846-a72cc700-db23-11eb-88cc-db8c664f9926.png)

**Comment by BNNorman** [comment]
Same settings for me. I used the web interface to create the end node. Like you I have a dragino on my desk for dev work and it picks up the gateway on the Humber bridge 11km away. I guess I'll just have to persevere - thanks for confirming the settings.

**Comment by pjb304** [comment]
If you hadn't said about it working fine in V2 I'd wonder about signal issues.  I've certainly seen it where the uplink gets through, but for whatever reason the downlink is never received when working in low signal areas.  I have a couple of gateways at home so signal strength isn't an issue for me.  Do let me know what the issue turns out to be, I'm curious.

**Comment by BNNorman** [comment]
I have a TTN indoor gateway which I 'bricked' trying to move it to V3 - only to find it  didn't work (after deleting the V2 gateway). 
And now the V2 console won't allow creation. So, I guess I have to wait till they sort out the TTIG. :-( Will let you know what I find out, if anything.
