### ISSUE TITLE
test.py has problem reading dragino.ini file

### ISSUE THREAD

**Issue by mariusfassa** [computenodes/dragino#9]
Hello,

I'm having a problem with the test.py. I'm using pi 3 B+ and dragino lora hat v1.4 with raspbian.
Here is what it tells me:

-------------------------------
pi@raspi:~/dragino-master $ ./test.py
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP
2021-04-17 11:48:24,532 - Dragino - 58 - DEBUG - Nonce = [133, 179]
2021-04-17 11:48:24,534 - DraginoConfig - 357 - CRITICAL - Missing required field 'gps_baud_rate'
Traceback (most recent call last):
  File "./test.py", line 13, in <module>
    D = Dragino("dragino.ini", logging_level=logging.DEBUG)
  File "/home/pi/dragino-master/dragino/dragino.py", line 67, in __init__
    self.config = DraginoConfig(config_filename, logging_level)
  File "/home/pi/dragino-master/dragino/dragino.py", line 358, in __init__
    raise DraginoError(err) from None
dragino.dragino.DraginoError: 'gps_baud_rate'
--------------------------------------------
I haven't modified dragino.ini.default except to put my TTN keys for ABP. But it seems to have a problem at the first line. (second if you don't count "#GPS configuration".

Thanks 
Marius

**Comment by ediiiiiiii** [comment]
If you open test.py you will see that it looks for a config file named dragino.ini (not dragino.ini.default)

**Comment by mariusfassa** [comment]
Thx for the answer. I'm ashamed it was something like that. I had already passed over the possibility as I remembered having tried changing the name already but I did it again and it worked. I need to verify everything twice or thrice...
